# Server Configuration
server.port=4000
spring.application.name=product-service
logging.level.root=INFO
logging.level.org.springframework.kafka=DEBUG


# ==========================
# DATABASE CONFIGURATION
# ==========================
#spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
#spring.datasource.username=admin_user
#spring.datasource.password=password
#
#
#
# ==========================
# KAFKA CONFIGURATION
# ==========================
# Broker Configuration

# Kafka bootstrap server (internal Docker network)
spring.kafka.bootstrap-servers=kafka:9092

# Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer


# Optional: Auto-create topics (matches Kafka broker setting)
spring.kafka.admin.auto-create=true
